config/routes.rb
Rails.application.routes.draw do
  get 'check_in/index'

  resources :participants

  resources :locations

  resources :events

  root 'events#index'

  get '/:tag' => 'check_in#index'
  post '/success' => 'check_in#success'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :locations
  has_many :participants
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :event
  has_and_belongs_to_many :participants, :autosave => true
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  serialize :visited_locations, Array
  belongs_to :event
  has_and_belongs_to_many :locations, :autosave => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/check_in_controller.rb
class CheckInController < ApplicationController
  def index
    @location = Location.find_by(tag: params[:tag])
  end

  def success
    @participant = Participant.find_by(email: params[:email])
    if @participant.nil? == false then
    @participant.visited_locations << params[:location_id].to_i
    @participant.save
  end
    respond_to do |format|
       if ! @participant.nil?
        format.html { redirect_to participant_path(@participant), notice: 'Participant was successfully checked in.' }
        format.json { render :show, status: :created, location: @participant }
      else
        @participant = Participant.create(:email => params[:email], :event_id => params[:event_id], :visited_locations => [params[:location_id].to_i])
        @participant.visited_locations << params[:location_id].to_i
      end
        if @participant.save
        Location.where(event_id: @participant.event_id).each do |l|
          l.participants << @participant
        end
        format.html { redirect_to participant_path(@participant), notice: 'Participant was successfully checked in.' }
        format.json { render :show, status: :created, location: @participant }
    end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @qr = RQRCode::QRCode.new("http://#{request.host}/#{@location.tag}", :size => 8)
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        # map the new location to each participant in the event
        Participant.where(event_id: @location.event_id).each do |p|
          p.locations << @location
        end
        format.html { redirect_to edit_event_path(@location.event_id), notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to edit_event_path(@location.event_id), notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to edit_event_path(@location.event_id), notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :tag, :event_id)
    end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        Location.where(event_id: @participant.event_id).each do |l|
          l.participants << @participant
        end
        format.html { redirect_to edit_event_path(@participant.event_id), notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to edit_event_path(@participant.event_id), notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to edit_event_path(@participant.event_id), notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:email, :event_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_in_helper.rb
module CheckInHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/check_in/index.html.erb
<center><coolheader><%= @location.name %></coolheader>
<br>
<br>
<br>

<%= form_tag('/success') do %>
 <h3> <div class="field">
    <%= label_tag :email %><br>
    <%= text_field_tag :email %>
  </div></h3><br>
  <%= hidden_field_tag :location_id, @location.id %>
  <%= hidden_field_tag :event_id, @location.event_id %>
  <div class="actions">
    <%= submit_tag "Check in" %>
  </div>
<% end %>
</center>

app/views/check_in/new.html.erb
<center><coolheader><%= @location.name %></coolheader>
<br>
<br>
<br>

<%= form_tag('/success') do %>
 <h3> <div class="field">
    <%= label_tag :email %><br>
    <%= text_field_tag :email %>
  </div></h3><br>
  <%= hidden_field_tag :location_id, @location.id %>
  <%= hidden_field_tag :event_id, @location.event_id %>
  <div class="actions">
    <%= submit_tag "Check in" %>
  </div>
<% end %>
</center>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <h3><%= f.label :name %></h3>
    <%= f.text_field :name %>
  </div>

  <h3>Locations</h3>

  <table class="table1">
    <thead>
      <tr>
        <th>Name</th>
        <th>Tag</th>
        <th>Event</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @event.locations.each do |location| %>
        <tr>
          <td><%= location.name %></td>
          <td><%= location.tag %></td>
          <td><%= location.event %></td>
          <td><%= link_to 'Show', location %></td>
          <td><%= link_to 'Edit', edit_location_path(location) %></td>
          <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'New Location', new_location_path({:event_id => @event.id}) %>

  <br>
  <br>

  <h3>Participants</h3>

  <table class="table1">
    <thead>
      <tr>
        <th>Email</th>
        <th>Event</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @event.participants.each do |participant| %>
        <tr>
          <td><%= participant.email %></td>
          <td><%= participant.event %></td>
          <td><%= link_to 'Show', participant %></td>
          <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
          <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <%= link_to 'New Participant', new_participant_path({:event_id => @event.id}) %>

  <br>
  <br>
  <br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<center><coolheader>Editing event</coolheader>
<br>
<br>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>
</center>

app/views/events/index.html.erb
<center><coolheader>Listing events</coolheader>
<br>
<br>
<br>

<table class="table1">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>
<button><%= link_to 'New Event', new_event_path %></button>
</center>

app/views/events/new.html.erb
<center><coolheader>New event</coolheader>
<br>
<br>
<%= render 'form' %>
<br>
<br>

<%= link_to 'Back', events_path %>
</center>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>


  <center><coolheader><%= @event.name %></coolheader>


<h3>Locations</h3>

<table class="table1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Tag</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event.locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= location.tag %></td>
        <td><%= location.event %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>

<h3>Participants</h3>

<table class="table1">
  <thead>
    <tr>
      <th>Email</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event.participants.each do |participant| %>
      <tr>
        <td><%= participant.email %></td>
        <td><%= participant.event %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScavengerHunt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3><div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div></h3>
  <h3><div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div></h3>
  <%= f.hidden_field :event_id, :value => @location.event_id.nil? ? params[:event_id] : @location.event_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<center><coolheader>Editing location</coolheader>
<br>
<br>
<%= render 'form' %>
<br>
<%= link_to 'Show', @location %> |
<%= link_to 'Back', edit_event_path(@location.event_id) %>
</center>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table class="table1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Tag</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= location.tag %></td>
        <td><%= location.event %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<center><coolheader>New location</coolheader>
<br>
<br>
<br>
<%= render 'form' %>

<%= link_to 'Back', edit_event_path(params[:event_id]) %>
</center>

app/views/locations/show.html.erb
<center><p id="notice"><%= notice %></p>

<h3>
  <strong>Name:</strong>
  <%= @location.name %>
</h3>
<br>
<table>
<% @qr.modules.each_index do |x| %>
  <tr>  
  <% @qr.modules.each_index do |y| %>
   <% if @qr.dark?(x,y) %>
    <td class="black"/>
   <% else %>
    <td class="white"/>
   <% end %>
  <% end %>
  </tr>
<% end %>
</table>
<br>
<h3>
  <strong>Event:</strong>
  <%= @location.event %>
</h3>
<br>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', event_path(@location.event_id) %>
</center>

app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3><div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div></h3>
  <%= f.hidden_field :event_id, :value => @participant.event_id.nil? ? params[:event_id] : @participant.event_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<center><coolheader>Editing participant</coolheader>
<br>
<br>
<br>
<%= render 'form' %>
<br>
<%= link_to 'Show', @participant %> |
<%= link_to 'Back', edit_event_path(@participant.event_id) %>
</center>

app/views/participants/index.html.erb
<h1>Listing participants</h1>

<table class="table1">
  <thead>
    <tr>
      <th>Email</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.email %></td>
        <td><%= participant.event %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<center><coolheader>New participant</coolheader>
<br>
<br>
<%= render 'form' %>

<%= link_to 'Back', edit_event_path(params[:event_id]) %>
</center>

app/views/participants/show.html.erb
<center></venter><p id="notice"><%= notice %></p>

<coolheader>
  <strong>Event:</strong>
  <%= @participant.event_id %>
</coolheader>
<br>
<br>

<h3>
  <strong>Email:</strong>
  <%= @participant.email %>
</h3>



<table class="table1">
  <thead>
    <tr>
      <th>Locations Left:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participant.locations.where(event_id: @participant.event_id).each do |l| %>
      <% if ! @participant.visited_locations.include? l.id %>
      <tr>
        <td><%= l.name %></td>
      </tr>
    <% end %>
  



<% end %>
</tbody>
</table><br>
<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', edit_event_path(@participant.event_id) %>
</center>